# This workflow deploys to staging.

# Credit to https://github.com/ericanastas/deploy-google-app-script-action for the
# essential instructions on authenticating GAS from GitHub Actions!

name: Deploy Staging

# Controls when the workflow will run
on:
  # Triggers the workflow on push to develop
  push:
    branches: [develop]


  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "deploy"
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Install clasp
        id: install-clasp
        run: sudo npm install @google/clasp@2.3.0 -g

      - name: Write CLASPRC_JSON secret to .clasprc.json file
        id: write-clasprc
        run: echo "$CLASPRC_JSON_SECRET" >> ~/.clasprc.json
        env:
          CLASPRC_JSON_SECRET: ${{ secrets.CLASPRC_JSON }}

      - name: Check clasp login status
        id: clasp-login
        run: clasp login --status

      - name: Checkout repo
        id: checkout-repo
        uses: actions/checkout@v2
        with:
          # Need to use personal access token to make sure action runs on `heroku` push
          token: ${{ secrets.REPO_ACCESS_TOKEN }}

      - name: Push Google Apps Script code
        id: clasp-push
        run: |
          cd google/src
          clasp push -f

      - name: Push Heroku code
        id: heroku-push
        run: git push origin `git subtree split --prefix heroku develop`:heroku --force
